# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160130_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time_stamp',
            field=models.CharField(max_length=128),
        ),
    ]
